CREATE TABLE users (
  id BIGINT UNSIGNED AUTO_INCREMENT COMMENT 'ユーザーID',
  name VARCHAR(100) NOT NULL COMMENT 'ユーザー名',
  email VARCHAR(100) NOT NULL COMMENT 'メールアドレス',
  password VARCHAR(255) NOT NULL COMMENT 'パスワード',
  role VARCHAR(20) NOT NULL DEFAULT 'user' COMMENT 'ロール',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  CONSTRAINT pk_users PRIMARY KEY (id)
) COMMENT='ユーザー情報';
