CREATE TABLE memos (
  id BIGINT UNSIGNED AUTO_INCREMENT COMMENT 'メモID',
  user_id BIGINT UNSIGNED NOT NULL COMMENT 'ユーザーID',
  content TEXT NOT NULL COMMENT '内容',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  CONSTRAINT pk_memos PRIMARY KEY (id),
  CONSTRAINT fk_memos_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) COMMENT='メモ情報';
